import type { traceIcons } from '@/components/timothy/trace-group'
import type { PermissionRequestEvent } from '@/api/types'
import type { AssistantState, ToolRun } from './chat'
import type { AgentPhase } from '@/components/chat/AgentStatusLine'

// toolCategory buckets a tool name into the trace icon registry
// (design contract 14.5): file/shell/web/mail/calendar/memory/kb/
// connector/other.
export function toolCategory(name: string): keyof typeof traceIcons {
  if (/read_file|write_file|list_files|edit/.test(name)) return 'file'
  if (/shell|run_command|bash/.test(name)) return 'shell'
  if (/search_web|fetch_url|http/.test(name)) return 'web'
  if (/mail/.test(name)) return 'mail'
  if (/calendar/.test(name)) return 'calendar'
  if (/memory|recall/.test(name)) return 'memory'
  if (/kb|knowledge/.test(name)) return 'kb'
  if (/^(google-calendar|mcp)[_-]/.test(name) || /[_-]/.test(name)) return 'connector'
  return 'other'
}

function capitalize(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1)
}

const targetKeys = ['path', 'file', 'command', 'cmd', 'query', 'url', 'name', 'collection', 'subject']

function truncate(s: string, max = 60): string {
  return s.length > max ? `${s.slice(0, max)}…` : s
}

// humanizeTool derives a display action and target from a tool run:
// action is the humanized name, target is the key argument.
export function humanizeTool(run: ToolRun): { action: string; target?: string } {
  const action = capitalize(run.name.replace(/[_-]/g, ' '))
  if (!run.args) return { action }
  let parsed: unknown
  try {
    parsed = JSON.parse(run.args)
  } catch {
    return { action }
  }
  if (typeof parsed !== 'object' || parsed === null) return { action }
  const obj = parsed as Record<string, unknown>
  for (const key of targetKeys) {
    const v = obj[key]
    if (typeof v === 'string' && v.length > 0) return { action, target: truncate(v) }
  }
  return { action }
}

// consequenceLine is deterministic, generated by the harness policy,
// never from the model's own claims (design contract 14.7).
export function consequenceLine(request: PermissionRequestEvent): string {
  const base =
    request.danger_level === 'destructive'
      ? 'Marked destructive by the tool policy: this can change or delete data and may not be reversible.'
      : "Runs on the Timothy server with this session's permissions and is expected to be reversible."
  const category = toolCategory(request.tool)
  if (category === 'shell') return `${base} Executes a shell command.`
  if (category === 'web' || category === 'mail' || category === 'connector') return `${base} Sends traffic outside Timothy.`
  return base
}

// agentPhaseFromState maps a live assistant turn to an AgentPhase.
// A finished (non-streaming) message is the caller's business: it
// decides whether to show a timed "done" line or fall back to idle.
export function agentPhaseFromState(
  msg: AssistantState | null,
  opts: { pendingPermission: boolean },
): AgentPhase {
  if (!msg || !msg.streaming) return { kind: 'idle' }
  if (opts.pendingPermission) return { kind: 'waiting', what: 'approval' }
  if (msg.error) return { kind: 'error', message: msg.error }
  const running = msg.tools.find((t) => t.status === 'running')
  if (running) return { kind: 'tool', tool: running.name }
  if (msg.text.length > 0) return { kind: 'streaming' }
  return { kind: 'thinking' }
}
