// Flat ISO 4217 code list the default-currency setting and mission
// budget picker both draw from — mirrors
// internal/brain/settings.allowedCurrencies exactly. No FX conversion,
// no per-currency formatting rules: just the codes.
export const CURRENCIES = [
  'USD',
  'EUR',
  'GBP',
  'JPY',
  'CNY',
  'INR',
  'BDT',
  'CHF',
  'CAD',
  'AUD',
  'NZD',
  'SEK',
  'NOK',
  'DKK',
  'PLN',
  'CZK',
  'HUF',
  'TRY',
  'AED',
  'SAR',
  'SGD',
  'HKD',
  'KRW',
  'TWD',
  'THB',
  'MYR',
  'IDR',
  'PHP',
  'VND',
  'BRL',
  'MXN',
  'ZAR',
  'ILS',
] as const
