// Package pdfgen orchestrates PDF generation over the pdfgen sidecar
// with content-hash caching: identical input (documents + options)
// reuses the attachment from a prior render instead of recompiling.
package pdfgen

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"io"

	"github.com/jackc/pgx/v5"

	"github.com/SumonMSelim/timothy/internal/brain/attachments"
	"github.com/SumonMSelim/timothy/internal/platform/pdfgen"
	"github.com/SumonMSelim/timothy/internal/platform/pgpool"
)

// generatorVersion is folded into the input hash so a template/layout
// change (a new sidecar build) invalidates every cached render without
// a schema migration.
const generatorVersion = "pdfgen/1"

// ErrNotEnabled reports a Service built with no sidecar configured
// (PDFGEN_URL unset). Callers surface this as a clear "not enabled"
// error rather than attempting a render.
var ErrNotEnabled = errors.New("pdfgen: pdf generation is not enabled")

// Result is a rendered PDF: either freshly generated or served from
// the input-hash cache.
type Result struct {
	AttachmentID string
	PDF          []byte
	Cached       bool
}

// Service renders markdown documents to PDF via the sidecar client,
// caching by content hash in the pdf_renders table and storing
// generated bytes through the attachment store.
type Service struct {
	client *pdfgen.Client
	db     *pgpool.Pool
	att    *attachments.Store
}

// New returns a Service. client nil means the sidecar isn't
// configured; callers should not construct a Service in that case and
// instead leave it nil so NotEnabled-style handling applies upstream
// (mirrors attachments.Store's nil-gating in cmd/brain/main.go).
func New(client *pdfgen.Client, db *pgpool.Pool, att *attachments.Store) *Service {
	return &Service{client: client, db: db, att: att}
}

// Render returns the PDF for docs+opts, generating it via the sidecar
// on a cache miss and storing the result as an attachment. A nil
// Service (or one built without a client) returns ErrNotEnabled.
func (s *Service) Render(ctx context.Context, docs []pdfgen.Document, opts pdfgen.Options) (Result, error) {
	if s == nil || s.client == nil {
		return Result{}, ErrNotEnabled
	}

	hash := inputHash(opts, docs)

	db, err := s.db.Get()
	if err != nil {
		return Result{}, fmt.Errorf("pdfgen: %w", err)
	}

	var attachmentID string
	err = db.QueryRow(ctx,
		"SELECT attachment_id FROM pdf_renders WHERE input_hash = $1", hash,
	).Scan(&attachmentID)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return Result{}, fmt.Errorf("pdfgen: lookup cache: %w", err)
	}
	if err == nil {
		r, _, openErr := s.att.Open(ctx, attachmentID)
		if openErr == nil {
			defer func() { _ = r.Close() }()
			pdf, readErr := io.ReadAll(r)
			if readErr != nil {
				return Result{}, fmt.Errorf("pdfgen: read cached attachment: %w", readErr)
			}
			return Result{AttachmentID: attachmentID, PDF: pdf, Cached: true}, nil
		}
		if !errors.Is(openErr, attachments.ErrNotFound) {
			return Result{}, fmt.Errorf("pdfgen: open cached attachment: %w", openErr)
		}
		// Attachment row is gone (e.g. manually cleaned up): treat as a
		// cache miss and regenerate below.
	}

	pdf, err := s.client.Render(ctx, docs, opts)
	if err != nil {
		return Result{}, fmt.Errorf("pdfgen: render: %w", err)
	}

	att, err := s.att.Save(ctx, bytes.NewReader(pdf))
	if err != nil {
		return Result{}, fmt.Errorf("pdfgen: store attachment: %w", err)
	}

	if _, err := db.Exec(ctx,
		"INSERT INTO pdf_renders (input_hash, attachment_id) VALUES ($1, $2) ON CONFLICT (input_hash) DO NOTHING",
		hash, att.ID,
	); err != nil {
		return Result{}, fmt.Errorf("pdfgen: cache insert: %w", err)
	}

	return Result{AttachmentID: att.ID, PDF: pdf, Cached: false}, nil
}

// inputHash hashes generatorVersion, opts and docs with every variable-
// length field length-prefixed (8-byte big-endian count/size ahead of
// the bytes), so no ambiguous field boundary can make two distinct
// inputs collide (e.g. a two-doc render can never hash the same as a
// one-doc render with concatenated content).
func inputHash(opts pdfgen.Options, docs []pdfgen.Document) string {
	h := sha256.New()
	writeString(h, generatorVersion)
	writeString(h, opts.CoverTitle)
	writeBool(h, opts.TOC)
	writeUint64(h, uint64(len(docs)))
	for _, d := range docs {
		writeString(h, d.Title)
		writeString(h, d.Content)
	}
	return hex.EncodeToString(h.Sum(nil))
}

func writeString(h io.Writer, s string) {
	writeUint64(h, uint64(len(s)))
	_, _ = io.WriteString(h, s)
}

func writeBool(h io.Writer, b bool) {
	if b {
		_, _ = h.Write([]byte{1})
	} else {
		_, _ = h.Write([]byte{0})
	}
}

func writeUint64(h io.Writer, n uint64) {
	var buf [8]byte
	binary.BigEndian.PutUint64(buf[:], n)
	_, _ = h.Write(buf[:])
}
